// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TyperProject;

#nullable disable

namespace TyperProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240328060944_SeedWords")]
    partial class SeedWords
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("TyperProject.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TyperProject.Records.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<float>("WordsPerMinute")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("TyperProject.Words.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WordString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WordString = "time"
                        },
                        new
                        {
                            Id = 2,
                            WordString = "year"
                        },
                        new
                        {
                            Id = 3,
                            WordString = "people"
                        },
                        new
                        {
                            Id = 4,
                            WordString = "way"
                        },
                        new
                        {
                            Id = 5,
                            WordString = "day"
                        },
                        new
                        {
                            Id = 6,
                            WordString = "man"
                        },
                        new
                        {
                            Id = 7,
                            WordString = "thing"
                        },
                        new
                        {
                            Id = 8,
                            WordString = "woman"
                        },
                        new
                        {
                            Id = 9,
                            WordString = "life"
                        },
                        new
                        {
                            Id = 10,
                            WordString = "child"
                        },
                        new
                        {
                            Id = 11,
                            WordString = "world"
                        },
                        new
                        {
                            Id = 12,
                            WordString = "school"
                        },
                        new
                        {
                            Id = 13,
                            WordString = "state"
                        },
                        new
                        {
                            Id = 14,
                            WordString = "family"
                        },
                        new
                        {
                            Id = 15,
                            WordString = "student"
                        },
                        new
                        {
                            Id = 16,
                            WordString = "group"
                        },
                        new
                        {
                            Id = 17,
                            WordString = "country"
                        },
                        new
                        {
                            Id = 18,
                            WordString = "problem"
                        },
                        new
                        {
                            Id = 19,
                            WordString = "hand"
                        },
                        new
                        {
                            Id = 20,
                            WordString = "part"
                        },
                        new
                        {
                            Id = 21,
                            WordString = "place"
                        },
                        new
                        {
                            Id = 22,
                            WordString = "case"
                        },
                        new
                        {
                            Id = 23,
                            WordString = "week"
                        },
                        new
                        {
                            Id = 24,
                            WordString = "company"
                        },
                        new
                        {
                            Id = 25,
                            WordString = "system"
                        },
                        new
                        {
                            Id = 26,
                            WordString = "program"
                        },
                        new
                        {
                            Id = 27,
                            WordString = "question"
                        },
                        new
                        {
                            Id = 28,
                            WordString = "work"
                        },
                        new
                        {
                            Id = 29,
                            WordString = "government"
                        },
                        new
                        {
                            Id = 30,
                            WordString = "number"
                        });
                });

            modelBuilder.Entity("TyperProject.Records.Record", b =>
                {
                    b.HasOne("TyperProject.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
